[package]
name = "strings"
version = "0.1.0"
authors = ["Fatih Bakir <mfatihbakir@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lidl = { path = "../../../runtime/rust" }
