$lidlmeta:
  name: lidl_example

my_struct:
  type: structure
  members:
    i: i8

string_struct:
  type: structure
  members:
    str: string

deep_struct:
  type: structure
  members:
    vec:
      type:
        name: vector
        parameters:
          - u8
    base: string_struct

complex_struct:
  type: structure
  members:
    v:
      type:
        name: vector
        parameters:
          - u8

example:
  type: service
  procedures:
    take_struct:
      returns:
        - i8
      parameters:
        str: my_struct
    echo_struct:
      returns:
        - my_struct
      parameters:
        str: my_struct
    take_complex:
      returns:
        - i8
      parameters:
        str: complex_struct
    echo_complex:
      returns:
        - complex_struct
      parameters:
        str: complex_struct

scientific_calculator:
  type: service
  procedures:
    add:
      returns:
        - f64
      parameters:
        left: f64
        right: f64
    multiply:
      returns:
        - f64
      parameters:
        left: f64
        right: f64
    log:
      returns:
        - f64
      parameters:
        val: f64

repeat:
  type: service
  procedures:
    echo:
      returns:
        - string_view
      parameters:
        message: string_view
    echo_bytes:
      returns:
        - name: span
          parameters:
            - u8
      parameters:
        arg:
          name: span
          parameters:
            - u8