calculator:
  type: service
  procedures:
    add:
      returns:
        - f64
      parameters:
        left: f64
        right: f64
    multiply:
      returns:
        - f64
      parameters:
        left: f64
        right: f64

device_types:
  type: enumeration
  members:
    - esp8266
    - nrf52
    - atmega328p

procedures:
  type: union
  variants:
    x: i32
    y: i64
