expected:
  type: generic<union>
  parameters:
    RetT: type
    ErrT: type
  variants:
    res: RetT
    err: ErrT

calculator:
  type: service
  procedures:
    add:
      returns:
        - name: expected
          parameters:
            - f64
            - i32
      parameters:
        left: f64
        right: f64
    multiply:
      returns:
        - f64
      parameters:
        left: f64
        right: f64

repeat:
  type: service
  procedures:
    echo:
      returns:
        - string
      parameters:
        message: string
