# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: ["push", "pull_request"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: run-cmake
      uses: lukka/run-cmake@v2.5
      if: "!contains( matrix.os, 'windows')"
      with:
        buildWithCMake: false
    
    - name: run-cmake
      uses: lukka/run-cmake@v2.5
      if: "contains( matrix.os, 'windows')"
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeAppendedArgs: '-G "Visual Studio 16 2019"'
        buildWithCMake: false
    
    - name: build lidlc
      run: cmake --build . -t lidlc
      working-directory: ${{ github.workspace }}/../../_temp
    
    - name: regenerate with lidlc
      run: cmake ${{ github.workspace }}
      working-directory: ${{ github.workspace }}/../../_temp
    
    - name: build everything
      run: cmake --build .
      working-directory: ${{ github.workspace }}/../../_temp
    
    - name: test
      run: ctest
      working-directory: ${{ github.workspace }}/../../_temp
