# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: ["push", "pull_request"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: run-cmake
      uses: lukka/run-cmake@v2.5
      with:
        buildWithCMake: false
    
    - name: build lidlc
      run: ninja lidlc
    
    - name: regenerate with lidlc
      run: cmake ..
    
    - name: build everything
      run: ninja
    
    - name: test
      run: ctest
